### ISSUE TITLE
Missing Plugs for WPS

### ISSUE THREAD

**Issue by rudgal** [HoLuLuLu/wps-office-multilang#1]
Hello there!

Just wanted to know whether there is a specific reason, why the WPS app doesn't have the some plugs compared to WPP And ET?
E.g. the removable-media plug is missing for WPS.
I noticed it, because i need to access other partitions and it was working for the other two apps but not for WPS.
```yaml
apps:
  et:
    command: usr/bin/et
    desktop: gui/et.desktop
    plugs:
    - alsa
    - cups-control
    - desktop
    - home
    - opengl
    - pulseaudio
    - removable-media
    - wayland
    - x11
  wpp:
    command: usr/bin/wpp
    desktop: gui/wpp.desktop
    plugs:
    - alsa
    - cups-control
    - desktop
    - home
    - opengl
    - pulseaudio
    - removable-media
    - wayland
    - x11
  wps:
    command: usr/bin/wps
    desktop: gui/wps.desktop
    plugs:
    - gsettings
    - home
    - pulseaudio
    - unity7
    - x11
    - opengl
    - cups-control
    - alsa
    - desktop
```
Regards, RG
